# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-publish:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "${CI_GIT_USER_KEY_FINGERPRINT}"
      - checkout
      - run: ./bin/publish-updated-projects.sh

workflows:
  version: 2
  master-commit:
    jobs:
      - build-and-publish
  hourly-project-update:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-publish
